
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5550129piyuelo
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  ##timeout: 5000

development:
  <<: *default
  database: blog_app_rod_development
  username: postgres

test:
  <<: *default
  database: blog_app_rod_test
  username: postgres

production:
  <<: *default
  database: blog_app_rod_production
  username: postgres
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
